'''
34. Write a Python program to compute the sum of the even-valued terms in the Fibonacci sequence whose values do not
exceed one million.
Note: Fibonacci series is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
'''

